accomodate changes to sweet

diff --git a/sbin/run-test-server b/sbin/run-test-server
--- a/sbin/run-test-server
+++ b/sbin/run-test-server
@@ -52,6 +52,11 @@ HELP_TEXT="
             under /run/secrets/<package>/client/test. Default is
             \"sftp-server\".
 
+        -w|--wait=secs
+            Do not return until the server container is listening for
+            connections or the number of secons have elapsed; in the later
+            case, kill the container and return an error.
+
         -h|--help
             Display help text and exit.
 "
@@ -61,9 +66,13 @@ USER_ARG=$DEFAULT_USER
 NETWORK=
 SFTP_PORT=2222
 CLIENT_PACKAGE=sftp-server
+WAIT=
+TMPLOG=/tmp/run-test-server.$$.log
 
 main () {
     processCommandLine "$@" || return 1
+
+    trap "rm -f ${TMPLOG} ; exit 255" 1 2 13 15
 
     setupNetwork ${NETWORK} || return
 
@@ -76,9 +85,31 @@ main () {
     moveKeyPairsToSecrets ${SFTP_CONT} || return 1
 
     echo "Starting container \"${SFTP_CONT}\""
-    docker start -a ${SFTP_CONT}
 
-    return $?
+    if [ ":$WAIT" != ":" ] ; then
+        currtime=`date +%s`
+        endtime=`expr ${currtime} + ${WAIT}`
+        nohup docker start -a ${SFTP_CONT} </dev/null >${TMPLOG} 2>&1 &
+        rc=0
+        while true ; do
+            if grep -q 'Server listening ' ${TMPLOG} ; then
+                break
+            fi
+            currtime=`date +%s`
+            if [ "${currtime}" -gt "${endtime}" ] ; then
+                rc=1
+                break
+            fi
+        done
+        cat ${TMPLOG}
+        rm -f "${TMPLOG}"
+
+    else
+        docker start -a ${SFTP_CONT}
+        rc=$?
+    fi
+
+    return $rc
 }
 
 setupNetwork () {
@@ -109,7 +140,7 @@ createStoppedSftpContainer () {
     container="$1"
     network="$2"
 
-    trap "docker rm -f ${container} >/dev/null 2>&1 ; exit 255" 1 2 13 15
+    trap "rm -f ${TMPLOG} ; docker rm -f ${container} >/dev/null 2>&1 ; exit 255" 1 2 13 15
     echo "Creating stopped container \"$container\""
     docker create --rm --name ${container} \
            -v /run/secrets -v /mnt \
@@ -193,7 +224,7 @@ DESCRIPTION$HELP_TEXT
 EOF
                 return 1 ;;
 
-            -[usnp]?*)
+            -[usnpw]?*)
                 opt=`expr "${arg}" : '\(-.\).*'`
                 rest=`expr "${arg}" : '-.\(.*\)'`
                 set : ${opt} "${rest}" "$@"
@@ -219,6 +250,14 @@ EOF
             
             -p|--package)
                 CLIENT_PACKAGE="$1"
+                shift ;;
+            
+            -w|--wait)
+                WAIT=`expr "$1" : '\([0-9][0-9]*\)$'`
+                if [ ":${WAIT}" = ":" ] ; then
+                    echo "$PROG: invalid -w|--wait value: \"$1\"" >&2
+                    exit 1
+                fi
                 shift ;;
             
             -*)
